version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - apiUrl=https://beta.prepdata.org
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "4002:3000"
    restart: always
    container_name: prep_legacy
