version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - rwApiUrl=https://staging-api.globalforestwatch.org/v1
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "4002:3000"
    restart: always
    container_name: prep-legacy
