FROM node:8.1.2

ENV DEBIAN_FRONTEND noninteractive
ENV NODE_ENV development

RUN apt-get update && \
    apt-get install -y bash git build-essential \
    automake autoconf make g++ libtool \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && npm install -g node-gyp --loglevel warn \
    && mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
RUN yarn install --silent

# Bundle app source
COPY . /usr/src/app

EXPOSE 3000

CMD ["yarn", "start"]
