// COMMONS
export const SET_MODAL_UNDER_DEVELOP = 'SET_MODAL_UNDER_DEVELOP';

// DATASETS
export const SWITCH_CHANGED = 'SWITCH_CHANGED';
export const SET_SWITCH_STATUS = 'SET_SWITCH_STATUS';
export const DATASET_LIST_RECEIVED = 'DATASET_LIST_RECEIVED';
export const DATASET_DETAIL_RECEIVED = 'DATASET_DETAIL_RECEIVED';

// DASHBOARDS
export const LIST_DASHBOARD_RECEIVED = 'LIST_DASHBOARD_RECEIVED';
export const DETAIL_DASHBOARD_RECEIVED = 'DETAIL_DASHBOARD_RECEIVED';

// INSIGHTS
export const LIST_INSIGHTS_RECEIVED = 'LIST_INSIGHTS_RECEIVED';
export const DETAIL_INSIGHTS_RECEIVED = 'DETAIL_INSIGHTS_RECEIVED';
