// COMMONS
export const SET_MODAL_UNDER_DEVELOP = 'SET_MODAL_UNDER_DEVELOP';

// DATAMAP
export const MAP_DATA_CHANGED = 'MAP_DATA_CHANGED';

// DATASETS
export const SWITCH_CHANGED = 'SWITCH_CHANGED';
export const SET_SWITCH_STATUS = 'SET_SWITCH_STATUS';
export const DATASET_FETCH_ERROR = 'DATASET_FETCH_ERROR';
export const DATASET_LIST_RECEIVED = 'DATASET_LIST_RECEIVED';
export const DATASET_DETAIL_RECEIVED = 'DATASET_DETAIL_RECEIVED';

// DASHBOARDS
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD_FETCH_ERROR';
export const DASHBOARD_LIST_RECEIVED = 'DASHBOARD_LIST_RECEIVED';
export const DASHBOARD_DETAIL_RECEIVED = 'DASHBOARD_DETAIL_RECEIVED';

// INSIGHTS
export const INSIGHTS_FETCH_ERROR = 'INSIGHTS_FETCH_ERROR';
export const INSIGHTS_LIST_RECEIVED = 'INSIGHTS_LIST_RECEIVED';
export const INSIGHTS_DETAIL_RECEIVED = 'INSIGHTS_DETAIL_RECEIVED';
