apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prep
  name: prep-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prep-app
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
