apiVersion: v1
kind: Service
metadata:
  namespace: prep
  labels:
    name: prep-app
  name: prep-app
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: prep-app
