// COMMONS
export const SET_MODAL_UNDER_DEVELOP = 'SET_MODAL_UNDER_DEVELOP';
export const SET_MODAL_SHARE = 'SET_MODAL_SHARE';
export const SET_MODAL_METADATA = 'SET_MODAL_METADATA';

// INFO SIDEBAR
export const SET_INFO_SIDEBAR_METADATA = 'SET_INFO_SIDEBAR_METADATA';

// Tooltip
export const SET_TOOLTIP = 'prep/SET_TOOLTIP';
export const TOOLTIP_TOGGLE = 'prep/TOOLTIP_TOGGLE';
export const TOOLTIP_SET_CHILDREN = 'prep/TOOLTIP_SET_CHILDREN';
export const TOOLTIP_LOADING = 'prep/TOOLTIP_LOADING';
export const TOOLTIP_SET_CHILDREN_PROPS = 'prep/TOOLTIP_SET_CHILDREN_PROPS';
export const TOOLTIP_SET_POSITION = 'prep/TOOLTIP_SET_POSITION';
export const TOOLTIP_FOLLOW_TOGGLE = 'prep/TOOLTIP_FOLLOW_TOGGLE';
export const TOOLTIP_DIRECTION = 'prep/TOOLTIP_DIRECTION';


// EXPLOREMAP
export const MAP_DATA_CHANGED = 'MAP_DATA_CHANGED';
export const SET_LAYER_STATUS = 'SET_LAYER_STATUS';
export const TOGGLE_LAYER_STATUS = 'TOGGLE_LAYER_STATUS';
export const MAP_LAYERS_ORDER_CHANGED = 'MAP_LAYER_ORDER_CHANGED';
export const MAP_LAYER_OPACITY_CHANGED = 'MAP_LAYER_OPACITY_CHANGED';
export const MAP_DATASET_ID_SELECTED = 'MAP_DATASET_ID_SELECTED';
export const MAP_DESELECT_DATASET = 'MAP_DESELECT_DATASET';
export const MAP_GEODATA_RECEIVED = 'MAP_GEODATA_RECEIVED';
export const MAP_GEOPOSITION_SET = 'MAP_GEOPOSITION_SET';
export const MAP_INTERACTION_VISIBILITY_SET = 'MAP_INTERACTION_VISIBILITY_SET';
export const CHANGE_TAB = 'CHANGE_TAB';
export const TABS_OPTIONS = [
  {
    label: 'Core datasets',
    value: 'core_datasets'
  },
  {
    label: 'All datasets',
    value: 'all_datasets'
  }
];
export const SET_BASEMAP = 'explore/SET_BASEMAP';
export const SET_LABELS = 'explore/SET_LABELS';
export const SET_BOUNDARIES = 'explore/SET_BOUNDARIES';

// DATASETS
export const DATASET_FETCH_ERROR = 'DATASET_FETCH_ERROR';
export const DATASET_LAYER_FETCH_ERROR = 'DATASET_LAYER_FETCH_ERROR';
export const DATASET_LIST_RECEIVED = 'DATASET_LIST_RECEIVED';
export const DATASET_LIST_RESET = 'DATASET_LIST_RESET';
export const DATASET_DETAIL_RECEIVED = 'DATASET_DETAIL_RECEIVED';
export const DATASET_WIDGET_RECEIVED = 'DATASET_WIDGET_RECEIVED';
export const DATASET_LAYER_RECEIVED = 'DATASET_LAYER_RECEIVED';
export const DATASET_METADATA_RECEIVED = 'DATASET_METADATA_RECEIVED';
export const DATASET_SET_FILTER = 'DATASET_SET_FILTER';

// LAYERS
export const LAYER_DATA_RECEIVED = 'LAYER_DATA_RECEIVED';
export const LAYER_DATA_ERROR = 'LAYER_DATA_ERROR';
export const SET_LAYERGROUP_ACTIVE_LAYER = 'SET_LAYERGROUP_ACTIVE_LAYER';

// DASHBOARDS
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD_FETCH_ERROR';
export const DASHBOARD_LIST_RECEIVED = 'DASHBOARD_LIST_RECEIVED';
export const DASHBOARD_DETAIL_RECEIVED = 'DASHBOARD_DETAIL_RECEIVED';

// INSIGHTS
export const INSIGHTS_FETCH_ERROR = 'INSIGHTS_FETCH_ERROR';
export const INSIGHTS_LIST_RECEIVED = 'INSIGHTS_LIST_RECEIVED';
export const INSIGHTS_DETAIL_RECEIVED = 'INSIGHTS_DETAIL_RECEIVED';

// PARTNERS
export const PARTNERS_FETCH_ERROR = 'PARTNERS_FETCH_ERROR';
export const PARTNERS_LIST_RECEIVED = 'PARTNERS_LIST_RECEIVED';

// LINKS
export const LINK_SHORTEN_RECEIVE = 'LINK_SHORTEN_RECEIVE';
export const LINK_SHORTEN_ERROR = 'LINK_SHORTEN_ERROR';

// Twitter Feed
export const TWITTER_FEED_FETCH_ERROR = 'TWITTER_FEED_FETCH_ERROR';
export const TWITTER_FEED_LIST_RECEIVED = 'TWITTER_FEED_LIST_RECEIVED';

// WIDGETS
export const WIDGET_DETAIL_RECEIVED = 'WIDGET_DETAIL_RECEIVED';
export const WIDGET_FETCH_ERROR = 'WIDGET_FETCH_ERROR';

// WIDGETS
export const RESOURCES_FETCH_ERROR = 'RESOURCES_FETCH_ERROR';
export const RESOURCES_LIST_RECEIVED = 'RESOURCES_LIST_RECEIVED';

// NEXGDDPTOOL
export const NEXGDDP_SET_MAP_ZOOM = 'NEXGDDP_SET_MAP_ZOOM';
export const NEXGDDP_SET_MAP_CENTER = 'NEXGDDP_SET_MAP_CENTER';
export const NEXGDDP_SET_MARKER_POSITION = 'NEXGDDP_SET_MARKER_POSITION';
export const NEXGDDP_SET_SEARCH = 'NEXGDDP_SET_SEARCH';
export const NEXGDDP_SET_MAP_MODE = 'NEXGDDP_SET_MAP_MODE';
export const NEXGDDP_SET_GRAPH_MODE = 'NEXGDDP_SET_GRAPH_MODE';
export const NEXGDDP_SET_SCENARIO_OPTIONS = 'NEXGDDP_SET_SCENARIO_OPTIONS';
export const NEXGDDP_SET_SCENARIO_SELECTION = 'NEXGDDP_SET_SCENARIO_SELECTION';
export const NEXGDDP_SET_RANGE1_OPTIONS = 'NEXGDDP_SET_RANGE1_OPTIONS';
export const NEXGDDP_SET_RANGE1_SELECTION = 'NEXGDDP_SET_RANGE1_SELECTION';
export const NEXGDDP_SET_RANGE2_OPTIONS = 'NEXGDDP_SET_RANGE2_OPTIONS';
export const NEXGDDP_SET_RANGE2_SELECTION = 'NEXGDDP_SET_RANGE2_SELECTION';
export const NEXGDDP_SET_CHART_DATA = 'NEXGDDP_SET_CHART_DATA';
export const NEXGDDP_SET_CHART_LOADED = 'NEXGDDP_SET_CHART_LOADED';
export const NEXGDDP_SET_CHART_ERROR = 'NEXGDDP_SET_CHART_ERROR';
