// COMMONS
export const SET_MODAL_UNDER_DEVELOP = 'SET_MODAL_UNDER_DEVELOP';
export const SET_MODAL_SHARE = 'SET_MODAL_SHARE';
export const SET_MODAL_METADATA = 'SET_MODAL_METADATA';

// EXPLOREMAP
export const MAP_DATA_CHANGED = 'MAP_DATA_CHANGED';
export const SET_LAYER_STATUS = 'SET_LAYER_STATUS';
export const TOGGLE_LAYER_STATUS = 'TOGGLE_LAYER_STATUS';

// DATASETS
export const DATASET_FETCH_ERROR = 'DATASET_FETCH_ERROR';
export const DATASET_LAYER_FETCH_ERROR = 'DATASET_LAYER_FETCH_ERROR';
export const DATASET_LIST_RECEIVED = 'DATASET_LIST_RECEIVED';
export const DATASET_DETAIL_RECEIVED = 'DATASET_DETAIL_RECEIVED';
export const DATASET_WIDGET_RECEIVED = 'DATASET_WIDGET_RECEIVED';
export const DATASET_LAYER_RECEIVED = 'DATASET_LAYER_RECEIVED';
export const DATASET_METADATA_RECEIVED = 'DATASET_METADATA_RECEIVED';
export const DATASET_SET_FILTER = 'DATASET_SET_FILTER';

// DASHBOARDS
export const DASHBOARD_FETCH_ERROR = 'DASHBOARD_FETCH_ERROR';
export const DASHBOARD_LIST_RECEIVED = 'DASHBOARD_LIST_RECEIVED';
export const DASHBOARD_DETAIL_RECEIVED = 'DASHBOARD_DETAIL_RECEIVED';

// INSIGHTS
export const INSIGHTS_FETCH_ERROR = 'INSIGHTS_FETCH_ERROR';
export const INSIGHTS_LIST_RECEIVED = 'INSIGHTS_LIST_RECEIVED';
export const INSIGHTS_DETAIL_RECEIVED = 'INSIGHTS_DETAIL_RECEIVED';

// PARTNERS
export const PARTNERS_FETCH_ERROR = 'PARTNERS_FETCH_ERROR';
export const PARTNERS_LIST_RECEIVED = 'PARTNERS_LIST_RECEIVED';

// LINKS
export const LINK_SHORTEN_RECEIVE = 'LINK_SHORTEN_RECEIVE';
export const LINK_SHORTEN_ERROR = 'LINK_SHORTEN_ERROR';

// Twitter Feed
export const TWITTER_FEED_FETCH_ERROR = 'TWITTER_FEED_FETCH_ERROR';
export const TWITTER_FEED_LIST_RECEIVED = 'TWITTER_FEED_LIST_RECEIVED';

// WIDGETS
export const WIDGET_DETAIL_RECEIVED = 'WIDGET_DETAIL_RECEIVED';
export const WIDGET_FETCH_ERROR = 'WIDGET_FETCH_ERROR';
